### PR TITLE
Gracefully truncate long definitions

### PR DESCRIPTION
**Pull request by dgw**
Draft because I built upon my previous PR.

Bumps minimum Sopel requirement from just `6` to `6.6.2`, which is when `tools.get_sendable_message()` appeared in the API.

It will be possible to use the whole 512-byte line length in Sopel 7.1, and I'll be happy to revise this implementation after release _if_ you would be OK with dropping support for all Sopel versions <7.1 in this plugin. Meanwhile, this approach just makes a conservative guess at how many bytes are available in the line after nickname/hostmask/target/etc.

### CODE REVIEW

**Comment by RustyBower** [comment]
Sweet. Let me know when it's good to review and I'll take a peek

**Comment by dgw** [comment]
@RustyBower It'll be good to review sometime after you merge #1. 😝

**Comment by RustyBower** [comment]
Touche ;)

Well #1 is merged so we're good to on this

**Comment by dgw** [comment]
I wish GitHub would recognize when commits from a PR are merged into the base branch from somewhere else, but it gave me an excuse to elaborate a bit more in the commit description. I guess. 😹

**Comment by RustyBower** [comment]
LGTM

**Pull request merged**
